[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[workspace]
members = [
    "generic",
    "value_profile",
    "gramatron",
    "grimoire",
    "nautilus",
    "token_level",
    "fuzzbench_util",
]
exclude = [
    "LibAFL",
]
